import prisma from '@/lib/prisma';
import { toCamelCase } from '@/utils/text/camelCase';
import { staticRecordId } from '../generate/staticRecordId';
import fs from 'fs';
import path from 'path';

// type asserted as any bc we need to access any model
const prismaClient = prisma as any;

// in-memory store for generated static records
const generatedRecords: { [key: string]: any } = {};

const processFileData = async (fileName: string, data: any, isDependency: boolean) => {
  let { modelName, seed, staticRecordName, staticRecordKeyName, dependencies, dependencyIterator, generateStaticRecord } = data;

  if (isDependency) {
    const dependencyData = (dependencies || []).reduce((acc: any, depName: string) => {
      if (!generatedRecords[depName]) {
        throw new Error(`💔 Unresolved dependency: ${depName} is required by ${fileName} but was not found.`);
      }
      acc[depName] = generatedRecords[depName];
      return acc;
    }, {});
    if (dependencyIterator) {
      if (!generatedRecords[dependencyIterator]) {
        throw new Error(`💔 Unresolved dependencyIterator: ${dependencyIterator} is required by ${fileName} but was not found.`);
      }
      const recordsToIterate = generatedRecords[dependencyIterator];
      const accumulatedSeeds: any[] = [];
      for (const key of Object.keys(recordsToIterate)) {
        const id = recordsToIterate[key];
        const result = seed({ key, id }, dependencyData);
        if (result) {
          accumulatedSeeds.push(...result);
        }
      }
      seed = accumulatedSeeds;
    } else {
      seed = seed(dependencyData);
    }
  }

  if (!prismaClient[modelName]) {
    console.warn(`💔 Skipping ${fileName}: Model ${modelName} does not exist on Prisma Client`);
    return;
  }

  if (!seed || !Array.isArray(seed)) {
    console.warn(`💔 Skipping ${fileName}: No seed array found`);
    return;
  }

  const exportName = staticRecordName ? staticRecordName : path.basename(fileName, '.ts');
  const keyName = staticRecordKeyName ? staticRecordKeyName : 'name';

  const seedData = generateStaticRecord === false
    ? seed
    : seed.map((record: any) =>
      record[keyName] != null
        ? { ...record, id: staticRecordId(exportName, toCamelCase(record[keyName])) }
        : record
    );

  console.log(`🌱  Seeding ${modelName}...`);

  const response = await prismaClient[modelName].createManyAndReturn({
    data: seedData,
  });
  console.log(`✅ Seeded ${response.length} records into ${modelName}.`);

  if (generateStaticRecord === false) {
    console.log(`⏭️  Skipping static record generation for ${fileName}.`);
    return;
  }

  const outputPath = path.join(__dirname, "..", "..", "configs", "staticRecords", fileName);
  const transformedRecords = response.reduce((acc: any, curr: any, index: number) => {
    const keyValue = curr[keyName];
    if (keyValue == null || typeof keyValue !== 'string') {
      throw new Error(
        `Cannot build static record: record at index ${index} has a missing or non-string value for key "${keyName}" ` +
        `(got ${JSON.stringify(keyValue)}). Set "staticRecordKeyName" in the data file to a field present on every record, ` +
        `or ensure each seeded record defines "${keyName}".\n  Offending record: ${JSON.stringify(curr)}`
      );
    }
    acc[toCamelCase(keyValue)] = curr.id;
    return acc;
  }, {});

  // store generated records in memory for dependent files
  generatedRecords[exportName] = transformedRecords;

  const fileContent = `// This file is auto-generated by the Lumexia Initialization script.
// Do not edit this file manually.

export const ${exportName} = ${JSON.stringify(transformedRecords, null, 2)} as const;
`;

  // ensure static records directory exists then write data
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, fileContent);
  console.log(`✅ ${exportName} data written to ${outputPath}`);
};

const Main = async () => {
  console.log('🌱 Starting the seed process...');

  // get the data files
  const dataDirPath = path.join(__dirname, 'data');
  const dataFiles = fs.readdirSync(dataDirPath);
  console.log(`📍 Found data files: ${dataFiles.join(', ')}`);

  const dependentFiles: { fileName: string, data: any }[] = [];
  const regularFiles: { fileName: string, data: any }[] = [];

  // separate files into regular and dependent
  for (const fileName of dataFiles) {
    const filePath = path.join(dataDirPath, fileName);
    const { data } = require(filePath);
    if (data.dependency) {
      dependentFiles.push({ fileName, data });
    } else {
      regularFiles.push({ fileName, data });
    }
  }

  // clear existing data before seeding. Dependent tables (children) must be cleared
  // before the regular tables (parents) they reference, otherwise the parent deleteMany
  // fails on re-runs with a foreign key constraint violation.
  console.log('🧹 Clearing existing data (dependent tables first)...');
  for (const file of [...dependentFiles, ...regularFiles]) {
    const { modelName } = file.data;
    if (!prismaClient[modelName]) continue;
    try {
      await prismaClient[modelName].deleteMany({});
    } catch (error) {
      throw new Error(`💔 Failed while clearing "${file.fileName}": ${(error as Error).message}`, { cause: error });
    }
  }

  console.log('🌱 Processing non-dependent files first...');
  for (const file of regularFiles) {
    try {
      await processFileData(file.fileName, file.data, false);
    } catch (error) {
      throw new Error(`💔 Failed while seeding "${file.fileName}": ${(error as Error).message}`, { cause: error });
    }
  }

  console.log('🌱 Processing dependent files...');
  for (const file of dependentFiles) {
    try {
      await processFileData(file.fileName, file.data, true);
    } catch (error) {
      throw new Error(`💔 Failed while seeding "${file.fileName}": ${(error as Error).message}`, { cause: error });
    }
  }
};

// execute the main function
Main()
  .catch((error) => {
    console.error('💔 An error occurred during initialization:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    console.log('🎉 Initialization process finished.');
  });
