import { toCamelCase } from '@/utils/text/camelCase';
import { staticRecordId } from './staticRecordId';
import fs from 'fs';
import path from 'path';

const dependencyProxy: any = new Proxy(() => dependencyProxy, {
  get: () => dependencyProxy,
  apply: () => dependencyProxy,
});

const processFileData = (fileName: string, data: any) => {
  const { staticRecordName, staticRecordKeyName, generateStaticRecord } = data;

  if (generateStaticRecord === false) {
    console.log(`⏭️  Skipping static record generation for ${fileName}.`);
    return;
  }

  let seed = data.seed;
  if (typeof seed === 'function') {
    seed = seed(dependencyProxy);
  }

  if (!Array.isArray(seed)) {
    console.warn(`⚠️ Skipping ${fileName}: seed is not an array, cannot generate keys.`);
    return;
  }

  const outputPath = path.join(__dirname, '..', '..', 'configs', 'staticRecords', fileName);
  const exportName = staticRecordName ? staticRecordName : path.basename(fileName, '.ts');
  const keyName = staticRecordKeyName ? staticRecordKeyName : 'name';

  const transformedRecords = seed.reduce((acc: any, curr: any) => {
    if (curr[keyName]) {
      const key = toCamelCase(curr[keyName]);
      // Must match scripts/initialization/main.ts, which seeds the same id.
      acc[key] = staticRecordId(exportName, key);
    } else {
      console.warn(`⚠️ Record in ${fileName} is missing the key '${keyName}'. Skipping.`);
    }
    return acc;
  }, {});

  const fileContent = `// This file is auto-generated by the Lumexia generation script.
// IDs are derived deterministically from each record's name (see
// scripts/generate/staticRecordId.ts) and match what the seeder inserts.
// Do not edit this file manually.

export const ${exportName} = ${JSON.stringify(transformedRecords, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, fileContent);
  console.log(`✅ ${exportName} generated to ${outputPath}`);
};

const Main = () => {
  console.log('🔧 Generating deterministic static records...');

  const dataDirPath = path.join(__dirname, '..', 'initialization', 'data');
  const dataFiles = fs.readdirSync(dataDirPath);
  console.log(`📍 Found data files: ${dataFiles.join(', ')}`);

  for (const fileName of dataFiles) {
    const filePath = path.join(dataDirPath, fileName);
    const { data } = require(filePath);
    processFileData(fileName, data);
  }

  console.log('🎉 Static record generation finished.');
};

try {
  Main();
} catch (error) {
  console.error('💔 An error occurred during static record generation:', error);
  process.exit(1);
}
