import { toCamelCase } from '@/utils/text/camelCase';
import fs from 'fs';
import path from 'path';

// Placeholder ID written for every static record key. It is intentionally not a
// real UUID: any Prisma `where: { id: PLACEHOLDER_ID }` simply matches nothing
// during the brief window between container boot and post-deploy regeneration.
const PLACEHOLDER_ID = '__SCAFFOLD__';

// Recursive proxy used to resolve dependency-based seed functions without a DB.
// Seed functions only read literal `name`/key fields off each record; the
// dependency values they assign elsewhere (e.g. `userRoleId: userRoles.production`)
// are never inspected here, so returning a proxy for any access is safe.
const dependencyProxy: any = new Proxy(() => dependencyProxy, {
  get: () => dependencyProxy,
  apply: () => dependencyProxy,
});

const processFileData = (fileName: string, data: any) => {
  const { staticRecordName, staticRecordKeyName, generateStaticRecord } = data;

  // Mirror the guard in generate/main.ts: skip config/settings tables that are
  // never referenced by static name.
  if (generateStaticRecord === false) {
    console.log(`⏭️  Skipping static record scaffold for ${fileName}.`);
    return;
  }

  // Resolve the seed into a plain array. Literal arrays are used as-is; function
  // seeds are invoked with a placeholder dependency proxy.
  let seed = data.seed;
  if (typeof seed === 'function') {
    seed = seed(dependencyProxy);
  }

  if (!Array.isArray(seed)) {
    console.warn(`⚠️ Skipping ${fileName}: seed is not an array, cannot scaffold keys.`);
    return;
  }

  const outputPath = path.join(__dirname, '..', '..', 'configs', 'staticRecords', fileName);
  const exportName = staticRecordName ? staticRecordName : path.basename(fileName, '.ts');
  const keyName = staticRecordKeyName ? staticRecordKeyName : 'name';

  const transformedRecords = seed.reduce((acc: any, curr: any) => {
    if (curr[keyName]) {
      acc[toCamelCase(curr[keyName])] = PLACEHOLDER_ID;
    } else {
      console.warn(`⚠️ Record in ${fileName} is missing the key '${keyName}'. Skipping.`);
    }
    return acc;
  }, {});

  const fileContent = `// This file is auto-generated by the Lumexia scaffold script.
// These are PLACEHOLDER values so the image can build and boot. Run
// \`npm run refresh-static-records\` after deploy to populate real IDs.
// Do not edit this file manually.

export const ${exportName} = ${JSON.stringify(transformedRecords, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, fileContent);
  console.log(`✅ ${exportName} scaffolded to ${outputPath}`);
};

const Main = () => {
  console.log('🔧 Scaffolding placeholder static records...');

  const dataDirPath = path.join(__dirname, '..', 'initialization', 'data');
  const dataFiles = fs.readdirSync(dataDirPath);
  console.log(`📍 Found data files: ${dataFiles.join(', ')}`);

  for (const fileName of dataFiles) {
    const filePath = path.join(dataDirPath, fileName);
    const { data } = require(filePath);
    processFileData(fileName, data);
  }

  console.log('🎉 Static record scaffolding finished.');
};

try {
  Main();
} catch (error) {
  console.error('💔 An error occurred during static record scaffolding:', error);
  process.exit(1);
}
