export const data = {
  modelName: 'appConfigGroup',
  staticRecordName: null,
  staticRecordKeyName: null,
  seed: [
    {
      "name": "company",
      "description": "company info"
    },
    {
      "name": "microForm",
      "description": "Responses for the autogenerated micro form"
    },
    {
      "name": "general",
      "description": "Catch all group. Generally for configs before config groups introduced"
    },
    {
      "name": "inventoryAudits",
      "description": "Thresholds and toggles for the weekly inventory audit trigger cron"
    }
  ],
};
