import { v4 as uuid } from 'uuid';
import { insert } from '../lib/db';
import { daysAgo, stamp } from '../lib/timeline';
import { appConfigGroups } from '@/configs/staticRecords/appConfigGroups';

// app config key/value rows. The microform group drives the autogenerated micro
// submission PDF header (submittedBy + lab contact); keys must match what
// generateMicroSubmissionForm reads.
const MICROFORM_CONFIGS = [
  { key: 'submittedBy', value: 'Kallista Ashworth' },
  { key: 'sendResultsToName', value: 'Kallista Ashworth' },
  { key: 'sendResultsToTelephone', value: '(555) 014-2207' },
  { key: 'sendResultsToEmail', value: 'qc@demo.lumexia' },
];

export const seedConfigs = async (): Promise<void> => {
  const createdAt = daysAgo(200);
  await insert(
    'config',
    MICROFORM_CONFIGS.map((c) => ({
      id: uuid(),
      key: c.key,
      value: c.value,
      dataType: 'string',
      description: '',
      configGroupId: appConfigGroups.microform,
      ...stamp(createdAt),
    })),
  );
};
